name: Bug report
description: Create a report to help us improve Sketchware Pro
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: You can drag and drop images here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### Device and Sketchware Pro-related info:
  - type: input
    id: device
    attributes:
      label: Device
      description: e.g. Xiaomi Note 10
      placeholder: Your device model
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      description: e.g. Android 13
      placeholder: Your Android OS version
    validations:
      required: true
  - type: input
    id: sketchware-pro-version
    attributes:
      label: Sketchware Pro version
      description: e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26
      placeholder: Your Sketchware Pro version
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any other relevant information.
    validations:
      required: false
